import api from './api';

const reportService = {
    generateReport: async (templateId, format = 'pdf') => {
        // Mock PDF generation with better formatting
        return new Promise((resolve) => {
            setTimeout(() => {
                const mockPdfContent = `===========================================
BUDGETWISE FINANCIAL REPORT
Template ID: ${templateId}
===========================================

Generated on: ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}

-------------------------------------------
INCOME SUMMARY
-------------------------------------------
Total Income:           ₹75,000
  - Salary:             ₹70,000
  - Other Income:       ₹5,000

-------------------------------------------
EXPENSE SUMMARY
-------------------------------------------
Total Expenses:         ₹45,000
  - Groceries:          ₹12,000
  - Transport:          ₹8,000
  - Entertainment:      ₹5,000
  - Utilities/Bills:    ₹20,000

-------------------------------------------
NET SAVINGS
-------------------------------------------
Amount:                 ₹30,000
Savings Rate:           40%

-------------------------------------------
NOTES
-------------------------------------------
This is a mock-up report generated by BudgetWise.
For actual financial data, connect your accounts
or input transactions manually.

-------------------------------------------
Report generated by BudgetWise
© 2025 Budget Wise - Smart Finance Management
===========================================
`;
                // Create a proper blob with text/plain type for better compatibility
                const blob = new Blob([mockPdfContent], { type: 'text/plain' });
                resolve({ data: blob });
            }, 1000);
        });
    },

    generateCustomReport: async (config) => {
        return new Promise((resolve) => {
            setTimeout(() => {
                const selectedMetrics = Object.entries(config.metrics)
                    .filter(([k, v]) => v)
                    .map(([k]) => `  - ${k.charAt(0).toUpperCase() + k.slice(1)}`)
                    .join('\n');

                const mockPdfContent = `===========================================
BUDGETWISE CUSTOM REPORT
${config.name}
===========================================

Generated on: ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}
Date Range: ${config.dateRange}

-------------------------------------------
SELECTED METRICS
-------------------------------------------
${selectedMetrics}

-------------------------------------------
FINANCIAL SUMMARY
-------------------------------------------
Total Income:           ₹75,000
Total Expenses:         ₹45,000
Net Savings:            ₹30,000
Savings Rate:           40%

-------------------------------------------
DETAILED BREAKDOWN
-------------------------------------------
Your custom report data would appear here
with detailed analysis based on the selected
metrics and date range.

-------------------------------------------
NOTES
-------------------------------------------
This is a custom mock-up report generated 
by BudgetWise based on your selections.

-------------------------------------------
Report generated by BudgetWise
© 2025 Budget Wise - Smart Finance Management
===========================================
`;
                const blob = new Blob([mockPdfContent], { type: 'text/plain' });
                resolve({ data: blob });
            }, 1200);
        });
    },

    getScheduledReports: () => api.get('/reports/scheduled'),

    scheduleReport: (config) => api.post('/reports/schedule', config),

    deleteScheduledReport: (id) => api.delete(`/reports/schedule/${id}`),
};

export default reportService;
